sudo: false
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - android-22
    - sys-img-armeabi-v7a-android-22
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
jdk:
    - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - echo "include ':app', ':commons'" > 'settings.gradle'
  - sed -i.bak '150,163d' $FLAKY_PATH

jobs:
  include:
    - stage: Lint (ktlint) ğŸš²ğŸ 
      script: ./gradlew ktlint
    - stage: Compile (Debug, UnitTest, AndroidTest & Release) ğŸŒš
      script: 
        - ./gradlew compileDebugAndroidTestSources
        - ./gradlew compileDebugSources
        - ./gradlew compileDebugUnitTestSources
        - ./gradlew compileReleaseSources
    - stage: Testing (Parallel integration & unit tests) ğŸ
      script: travis_wait 30 ./testing integration_tests
    - script: ./testing unit_tests

notifications:
  email:
    on_success: never
